# Generated by Django 2.2.3 on 2019-07-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_auto_20190708_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodata',
            name='GPSstring',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='GPStime',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='GPSx',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='GPSy',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
    ]
