# Generated by Django 2.2.3 on 2019-07-09 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('practice', '0004_auto_20190708_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForCallculations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GPSstring', models.CharField(default='', max_length=70)),
                ('GPStime', models.BigIntegerField(default=0)),
                ('GPSx', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('GPSy', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('AccX', models.DecimalField(decimal_places=5, max_digits=8)),
                ('AccY', models.DecimalField(decimal_places=5, max_digits=8)),
                ('AccZ', models.DecimalField(decimal_places=5, max_digits=8)),
                ('GiroXY', models.DecimalField(decimal_places=4, max_digits=6)),
                ('GiroXZ', models.DecimalField(decimal_places=4, max_digits=6)),
                ('GiroYZ', models.DecimalField(decimal_places=4, max_digits=6)),
                ('Speed', models.DecimalField(decimal_places=5, max_digits=8)),
                ('AngAcc', models.DecimalField(decimal_places=4, max_digits=6)),
                ('NumOvertake', models.BigIntegerField()),
                ('SpeedType', models.CharField(choices=[('Lx', 'Низкая скорость'), ('NR', 'Средняя скорость'), ('Hg', 'Высокая скорость')], default='NR', max_length=2)),
                ('UserType', models.CharField(choices=[('FR', 'Новичок'), ('CF', 'Уверенный водитель'), ('DR', 'Опасное вождение')], default='FR', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
