# Generated by Django 2.2.3 on 2019-07-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0006_auto_20190709_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forcallculations',
            name='AccX',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='forcallculations',
            name='AccY',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='forcallculations',
            name='AccZ',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='forcallculations',
            name='AngAcc',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='forcallculations',
            name='GiroXY',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='forcallculations',
            name='GiroXZ',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='forcallculations',
            name='GiroYZ',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='forcallculations',
            name='Speed',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='AccX',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='AccY',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='AccZ',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='GiroXY',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='GiroXZ',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='GiroYZ',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
    ]
