# Generated by Django 2.2.3 on 2019-07-09 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0008_auto_20190709_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forcallculations',
            name='GPSstring',
            field=models.CharField(default='', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='forcallculations',
            name='GPStime',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forcallculations',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='GPSstring',
            field=models.CharField(default='', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='GPStime',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
